# global variables
gender_options = {"F": "Female",
                  "M": "Male",
                  "X": "Other",
                  "0": "Prefer not to say"}

course_options =   ('Agriculture',
                    'Anthropology',
                    'Archaeology',
                    'Architecture and design',
                    'Area studies',
                    'Business and Management',
                    'Computer Science',
                    'Culinary arts',
                    'Economics',
                    'Education',
                    'Engineering and technology',
                    'Environmental studies and forestry',
                    'Ethnic and cultural studies',
                    'Gender and sexuality studies',
                    'Geography',
                    'History',
                    'Human physical performance and recreation',
                    'Journalism, media studies and communication',
                    'Law',
                    'Linguistics and languages',
                    'Literature',
                    'Mathematics',
                    'Medicine',
                    'Natural Sciences',
                    'Performing arts',
                    'Philosophy',
                    'Political science',
                    'Psychology',
                    'Religion',
                    'Social work',
                    'Sociology',
                    'Visual arts')

degree_options = ("Bachelors (first cycle)",
                  "Masters (second cycle)",
                  "Doctorate")
